baseURL = 'http://togarashimayo.com/'
languageCode = 'en-us'
title = 'Mich Chan 🦈'
theme = 'togarashimayo'
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
other-configs = "your-configs"


[menu]

  [[menu.main]]
  name = "Instagram"
  weight = 100
  identifier = "instagram"
  url = "/instagram/"

[params]
your-params-config = your-params-config
robots = [
  "AdsBot-Google",
  "Amazonbot",
  "anthropic-ai",
  "Applebot",
  "Applebot-Extended",
  "AwarioRssBot",
  "AwarioSmartBot",
  "Bytespider",
  "CCBot",
  "ChatGPT",
  "ChatGPT-User",
  "Claude-Web",
  "ClaudeBot",
  "cohere-ai",
  "DataForSeoBot",
  "Diffbot",
  "FacebookBot",
  "Google-Extended",
  "GPTBot",
  "ImagesiftBot",
  "magpie-crawler",
  "omgili",
  "Omgilibot",
  "peer39_crawler",
  "PerplexityBot",
  "YouBot"
]